### ISSUE TITLE
Readme faltando

### ISSUE THREAD

**Issue by matbrgz** [Thalyta-dev/consumerApiTrello#1]
Eii da uma melhorada no readme, assim todos podem saber do que se trata o projeto.

**Comment by Thalyta-dev** [comment]
Que fofo, você viu. Haha <3 obrigada. Vou melhorar.Em 4 de fev de 2021 21:12, Matheus Breguêz <notifications@github.com> escreveu:
Eii da uma melhorada no readme, assim todos podem saber do que se trata o projeto.
